### ISSUE TITLE
반말 사용.

### ISSUE THREAD

**Issue by taeguk** [utilForever/ModernCppCookbook#1]
존댓말 사이에 반말 사용이 보여서 이슈 드립니다 ㅎㅎ
![image](https://user-images.githubusercontent.com/9107889/29979804-f238a288-8f81-11e7-9957-3d9c8e5fd94d.png)

**Comment by utilForever** [comment]
감사합니다. 확인 후 수정하겠습니다.

**Comment by utilForever** [comment]
32f77b0에서 수정했습니다.
