### ISSUE TITLE
Couldn't see the string inside the angle bracket on md

### ISSUE THREAD

**Issue by pr0gr4m** [utilForever/ModernCppCookbook#2]
Refer the comments on the link https://github.com/utilForever/ModernCppCookbook/commit/cc5791161efe0c590c8b2a879b6cc24e73ca0eb1

**Comment by utilForever** [comment]
Oh, I missed write the angle bracket. Thanks! lol

**Comment by utilForever** [comment]
Fix in e9fc72b
