### ISSUE TITLE
매끄럽지 않은 문장

### ISSUE THREAD

**Issue by Surpreem** [utilForever/ModernCppCookbook#6]
> 표준 I/O는 스트림 모델을 가집니다. 따라서 이름은 ```<iostream>```입니다.

이 문장이 다소 매끄럽지 않은데 어떻게 고치는 게 나을지 잘 생각이 안 나네요.

> 표준 I/O는 스트림 모델로 이름은 ```<iostream>```입니다.

이것도 매끄럽지 않기는 마찬가지 인데 더 나은 문장은 아직 생각이 안 나네요.

**Comment by utilForever** [comment]
> 모든 입출력은 스트림 모델을 따릅니다. 표준 I/O도 마찬가지입니다. 이를 반영해 ```<iostream>```이라는 이름을 갖습니다.
이건 어떨까요?

**Comment by Surpreem** [comment]
> 모든 입출력은 스트림 모델을 따릅니다. 표준 I/O도 마찬가지이며 이를 반영해 ```<iostream>```이라고 합니다.

적으신 내용을 살짝 고쳐봤습니다.

**Comment by utilForever** [comment]
> 모든 입출력은 스트림 모델을 따릅니다. 표준 I/O도 마찬가지이며 이를 반영해 ```<iostream>```이라는 이름 사용합니다.

저도 적으신 내용을 살짝 고쳐봤습니다.

**Comment by Surpreem** [comment]
이 정도로 마무리하는 것도 좋을 듯합니다.

**Comment by utilForever** [comment]
네 ^^ 다듬어주셔서 감사합니다.

**Comment by utilForever** [comment]
2d9a5c1 에서 수정합니다.
