### ISSUE TITLE
코드에서 문자 상수 표현

### ISSUE THREAD

**Issue by Surpreem** [utilForever/ModernCppCookbook#9]
2장 ```ArgcArgvTest``` 코드에서 다음 부분에 대한 내용입니다.
``` C++
std::cout << argv[i] << "\n";
```
```"\n"```을 ```'\n'```로 표현하는 게 어떨까요. 문자 상수든 문자열 상수든 모두 큰 따옴표로 감싸도 상관 없지만 코드에서는 가급적 차이를 드러내는 것도 좋다고 생각합니다. 이는 1장에서 문자열 상수를 큰 따옴표로 묶는다는 것만 언급한 부분과도 관련이 있습니다.

물론 문자와 문자열에 대한 차이를 궁금해 하겠지만 자세한 것은 해당 항목에서 다루면 될 테고요.

**Comment by utilForever** [comment]
좋은 의견입니다. 반영하겠습니다.
